### ISSUE TITLE
Extension is not working

### ISSUE THREAD

**Issue by MetropolisCZ** [francisrhee/musescore-downloader#1]
Hello, I tried to use your extension, but it doesn´t work. On click on the extension button, only blank square will show ![image](https://user-images.githubusercontent.com/48151954/82764429-ef50c480-9e0e-11ea-8cb0-43f6a6f421c0.png). I have tried on the new canary Edge and on Chrome. Error list is: 
![image](https://user-images.githubusercontent.com/48151954/82764474-3474f680-9e0f-11ea-9ecb-97597afc0786.png)
![image](https://user-images.githubusercontent.com/48151954/82764477-4060b880-9e0f-11ea-995b-c57b94fea082.png)

**Comment by francisrhee** [comment]
Hi, the extension was still in development when this issue was created. It should be somewhat working now, please take a look.
